import "server-only";

export const MEETING_ERROR_CODES = {
  AVAILABILITY_ERROR: "AVAILABILITY_ERROR",
  AVAILABILITY_UNAVAILABLE: "AVAILABILITY_UNAVAILABLE",
  INVALID_TIMEZONE: "INVALID_TIMEZONE",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  INVALID_DATE: "INVALID_DATE",
  DATE_OUT_OF_RANGE: "DATE_OUT_OF_RANGE",
  MEETING_ERROR: "MEETING_ERROR",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  IDEMPOTENCY_REPLAY: "IDEMPOTENCY_REPLAY",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  LINK_NOT_ACTIVE: "LINK_NOT_ACTIVE",
  BOOKING_TEMPORARILY_UNAVAILABLE: "BOOKING_TEMPORARILY_UNAVAILABLE",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  RATE_LIMITED: "RATE_LIMITED",
} as const;

export type MeetingErrorCode = (typeof MEETING_ERROR_CODES)[keyof typeof MEETING_ERROR_CODES];

export const MEETING_RESPONSE_CODES = {
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  AVAILABILITY_AVAILABLE: "AVAILABILITY_AVAILABLE",
} as const;

export type MeetingResponseCode = (typeof MEETING_RESPONSE_CODES)[keyof typeof MEETING_RESPONSE_CODES];
