import "server-only";

export const MEETING_ERROR_CODES = {
  AVAILABILITY_ERROR: "AVAILABILITY_ERROR",
  MEETING_ERROR: "MEETING_ERROR",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  IDEMPOTENCY_REPLAY: "IDEMPOTENCY_REPLAY",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
} as const;

export type MeetingErrorCode = (typeof MEETING_ERROR_CODES)[keyof typeof MEETING_ERROR_CODES];

export const MEETING_RESPONSE_CODES = {
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  AVAILABILITY_AVAILABLE: "AVAILABILITY_AVAILABLE",
} as const;

export type MeetingResponseCode = (typeof MEETING_RESPONSE_CODES)[keyof typeof MEETING_RESPONSE_CODES];
